import type { FeedData } from './types';

export const FEED_DATA: FeedData = {
  schemaVersion: 3,
  categories: [
    { slug: 'environment', name: 'Environment' },
    { slug: 'git', name: 'Git' },
    { slug: 'dependencies', name: 'Dependencies' },
    { slug: 'build', name: 'Build' },
    { slug: 'tests', name: 'Tests' },
    { slug: 'docker', name: 'Docker' },
    { slug: 'security', name: 'Security' },
    { slug: 'code_quality', name: 'Code Quality' },
    { slug: 'database', name: 'Database' },
    { slug: 'ci_cd', name: 'CI/CD' },
    { slug: 'deployment', name: 'Deployment' },
    { slug: 'api_check', name: 'API Check' },
    { slug: 'performance', name: 'Performance' },
    { slug: 'monitoring', name: 'Monitoring' },
    { slug: 'rollback', name: 'Rollback' },
    { slug: 'post_deployment', name: 'Post-Deploy' },
  ],
  stages: [
    'Discover',
    'Config',
    'Git',
    'Dependencies',
    'Code Quality',
    'Tests',
    'Build',
    'Database',
    'Docker',
    'CI/CD',
    'Deployment',
    'Security',
    'API Check',
    'Performance',
    'Monitoring',
    'Rollback',
    'Post-Deploy',
    'Ship',
  ],
  thresholds: {
    ready: 80,
    warning: 60,
  },
  // Per-category influence on the overall ship score (weights sum to 100).
  // Security and build remain dominant; softer signals get smaller shares.
  categoryWeights: {
    security: 20,
    build: 15,
    tests: 12,
    code_quality: 8,
    api_check: 8,
    deployment: 7,
    dependencies: 6,
    post_deployment: 5,
    performance: 5,
    monitoring: 4,
    database: 4,
    git: 4,
    ci_cd: 3,
    docker: 3,
    rollback: 2,
    environment: 1,
  },
};
